#!/usr/bin/env python3
"""Generate src/h264/deblock_tables.rs (ITU-T Table 8-16/8-17 alpha/beta/tc0)
from FFmpeg's h264_loopfilter.c. The values are the H.264 spec thresholds; we
emit the meaningful 52-entry slice of FFmpeg's padded [52*3] tables, indexed by
the clamped QP.
"""
import re
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "vendor", "h264_loopfilter.c")
OUT = os.path.join(ROOT, "src", "h264", "deblock_tables.rs")


def grab(text, name):
    i = text.index(name)
    i = text.index("{", i)
    d = 0
    j = i
    while j < len(text):
        if text[j] == "{":
            d += 1
        elif text[j] == "}":
            d -= 1
            if d == 0:
                break
        j += 1
    return [int(x) for x in re.findall(r"-?\d+", text[i + 1 : j])]


def main():
    t = re.sub(r"/\*.*?\*/", "", open(SRC).read(), flags=re.S)
    alpha = grab(t, "alpha_table[52*3]")
    beta = grab(t, "beta_table[52*3]")
    tc0 = grab(t, "tc0_table[52*3][4]")  # 156*4 flat

    a = [alpha[52 + q] for q in range(52)]
    b = [beta[52 + q] for q in range(52)]
    tc = [(tc0[4 * (52 + q) + 1], tc0[4 * (52 + q) + 2], tc0[4 * (52 + q) + 3]) for q in range(52)]
    assert a[16] == 4 and a[51] == 255
    assert b[16] == 2 and b[51] == 18

    with open(OUT, "w") as f:
        f.write("//! H.264 deblocking thresholds (ITU Table 8-16/8-17), generated by\n")
        f.write("//! scripts/gen_h264_deblock_tables.py from FFmpeg's h264_loopfilter.c.\n\n")
        f.write("pub const ALPHA: [u8; 52] = [\n    " + ", ".join(map(str, a)) + ",\n];\n\n")
        f.write("pub const BETA: [u8; 52] = [\n    " + ", ".join(map(str, b)) + ",\n];\n\n")
        f.write("/// tc0 indexed [indexA][bS-1], bS in 1..=3.\n")
        f.write("pub const TC0: [[u8; 3]; 52] = [\n")
        for (x, y, z) in tc:
            f.write(f"    [{x}, {y}, {z}],\n")
        f.write("];\n")
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
