#!/usr/bin/env python3
"""Generate src/x509_roots.rs — the trusted root CA store for Veil's TLS client.

Reads the Mozilla CA bundle (certifi, the same set Firefox ships) and emits the
SHA-256 of each root's Subject DN (DER). Veil anchors a presented certificate
chain by checking that its top issuer's Subject-DN hash is in this set.
"""
import hashlib
import sys

try:
    import certifi
    from cryptography import x509
    from cryptography.hazmat.primitives.serialization import Encoding
except Exception as e:  # pragma: no cover
    sys.stderr.write(f"gen_roots: {e}\n")
    sys.exit(0)  # tolerate: the committed file is the fallback

bundle = certifi.where()
pem = open(bundle, "rb").read()
blocks = pem.split(b"-----END CERTIFICATE-----")
hashes = set()
for b in blocks:
    i = b.find(b"-----BEGIN CERTIFICATE-----")
    if i < 0:
        continue
    block = b[i:] + b"-----END CERTIFICATE-----\n"
    try:
        cert = x509.load_pem_x509_certificate(block)
    except Exception:
        continue
    dn_der = cert.subject.public_bytes()
    hashes.add(hashlib.sha256(dn_der).digest())

hashes = sorted(hashes)
out = []
out.append("// Auto-generated by scripts/gen_roots.py from the Mozilla CA bundle (certifi).")
out.append("// Each entry is SHA-256(Subject DN DER) of a trusted root CA.")
out.append(f"pub const TRUSTED_ROOT_DN_HASHES: [[u8; 32]; {len(hashes)}] = [")
for h in hashes:
    body = ", ".join(f"0x{x:02x}" for x in h)
    out.append(f"    [{body}],")
out.append("];")
open("src/x509_roots.rs", "w").write("\n".join(out) + "\n")
print(f"gen_roots: wrote {len(hashes)} trusted roots")
