#!/usr/bin/env python3
"""Generate src/h264/cavlc_tables.rs from FFmpeg's h264_cavlc.c VLC tables.

These (length, codeword) arrays ARE the ITU-T H.264 Table 9-5/9-7/9-9/9-10
spec tables (facts, not creative work); we re-emit them as Rust const arrays
so the from-scratch CAVLC reader can do prefix matching. Indexing convention:
coeff_token[cat][total_coeff*4 + trailing_ones]; total_zeros[total_coeff-1][zeros];
run_before[min(zeros_left-1,6)][run].
"""
import re
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "vendor", "h264_cavlc.c")
OUT = os.path.join(ROOT, "src", "h264", "cavlc_tables.rs")


def grab_body(text, name):
    i = text.index(name)
    i = text.index("{", i)
    depth = 0
    j = i
    while j < len(text):
        if text[j] == "{":
            depth += 1
        elif text[j] == "}":
            depth -= 1
            if depth == 0:
                break
        j += 1
    return text[i + 1 : j]


def grab_flat(text, name):
    return [int(x) for x in re.findall(r"-?\d+", grab_body(text, name))]


def grab_padded(text, name, rows, cols):
    """Parse a 2-D ragged C initializer into rows×cols, zero-padding short
    rows and missing rows (C semantics)."""
    body = grab_body(text, name)
    out = [[0] * cols for _ in range(rows)]
    r = 0
    for m in re.finditer(r"\{([^{}]*)\}", body):
        vals = [int(x) for x in re.findall(r"-?\d+", m.group(1))]
        for c, v in enumerate(vals[:cols]):
            out[r][c] = v
        r += 1
    flat = []
    for row in out:
        flat.extend(row)
    return flat


def main():
    text = open(SRC).read()
    text = re.sub(r"/\*.*?\*/", "", text, flags=re.S)
    text = re.sub(r"//[^\n]*", "", text)

    ct_len = grab_flat(text, "coeff_token_len[4][4*17]")   # 4*68
    ct_bits = grab_flat(text, "coeff_token_bits[4][4*17]")
    cdc_len = grab_flat(text, "chroma_dc_coeff_token_len[4*5]")  # 20
    cdc_bits = grab_flat(text, "chroma_dc_coeff_token_bits[4*5]")
    tz_len = grab_padded(text, "total_zeros_len[16][16]", 16, 16)
    tz_bits = grab_padded(text, "total_zeros_bits[16][16]", 16, 16)
    cdtz_len = grab_padded(text, "chroma_dc_total_zeros_len[3][4]", 3, 4)
    cdtz_bits = grab_padded(text, "chroma_dc_total_zeros_bits[3][4]", 3, 4)
    run_len = grab_padded(text, "run_len[7][16]", 7, 16)
    run_bits = grab_padded(text, "run_bits[7][16]", 7, 16)

    assert len(ct_len) == 4 * 68, len(ct_len)
    assert len(tz_len) == 256, len(tz_len)
    assert len(run_len) == 112, len(run_len)

    def emit_flat(f, name, ty, data):
        f.write(f"pub const {name}: [{ty}; {len(data)}] = [\n")
        for k in range(0, len(data), 16):
            f.write("    " + ",".join(str(x) for x in data[k : k + 16]) + ",\n")
        f.write("];\n\n")

    with open(OUT, "w") as f:
        f.write("//! H.264 CAVLC VLC tables (ITU-T Table 9-5/9-7/9-9/9-10), generated by\n")
        f.write("//! scripts/gen_h264_tables.py from FFmpeg's h264_cavlc.c. Do not edit.\n")
        f.write("//! Layout: coeff_token[cat*68 + total_coeff*4 + trailing_ones];\n")
        f.write("//! total_zeros[(total_coeff-1)*16 + zeros]; run_before[min(zl-1,6)*16 + run].\n\n")
        emit_flat(f, "COEFF_TOKEN_LEN", "u8", ct_len)
        emit_flat(f, "COEFF_TOKEN_BITS", "u16", ct_bits)
        emit_flat(f, "CHROMA_DC_COEFF_TOKEN_LEN", "u8", cdc_len)
        emit_flat(f, "CHROMA_DC_COEFF_TOKEN_BITS", "u16", cdc_bits)
        emit_flat(f, "TOTAL_ZEROS_LEN", "u8", tz_len)
        emit_flat(f, "TOTAL_ZEROS_BITS", "u16", tz_bits)
        emit_flat(f, "CHROMA_DC_TOTAL_ZEROS_LEN", "u8", cdtz_len)
        emit_flat(f, "CHROMA_DC_TOTAL_ZEROS_BITS", "u16", cdtz_bits)
        emit_flat(f, "RUN_LEN", "u8", run_len)
        emit_flat(f, "RUN_BITS", "u16", run_bits)

    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
