#!/usr/bin/env python3
"""M34 T5: pre-rasterize a handful of Google Fonts into a no_std Rust source
file (src/fonts_generated.rs) of 1-bpp bitmap glyphs, so the Veil browser can
render real typefaces (selected via CSS font-family/weight/style).

Standalone: `python3 scripts/gen_fonts.py`. Downloads the TTFs into
assets/fonts/ (cached) and regenerates src/fonts_generated.rs. Needs Pillow
(`pip install --break-system-packages Pillow`). Build.sh runs it.

Each variant is rasterized at 16px and 24px for printable ASCII (0x20-0x7E).
Glyphs are variable-width: per glyph we store (advance, bit width) and a 1-bpp,
row-major bitmap (advance px wide, font-height px tall, baseline-aligned).
"""
import os
import sys
import urllib.request

try:
    from PIL import Image, ImageDraw, ImageFont
except ImportError:
    sys.stderr.write("Pillow required: pip install --break-system-packages Pillow\n")
    sys.exit(1)

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
FONTDIR = os.path.join(ROOT, "assets", "fonts")
OUT = os.path.join(ROOT, "src", "fonts_generated.rs")
RAW = "https://github.com/google/fonts/raw/main/ofl/"

# (local filename, repo path) — variable fonts carry a [wght] axis.
TTFS = {
    "cormorant.ttf": "cormorantgaramond/CormorantGaramond%5Bwght%5D.ttf",
    "cormorant-italic.ttf": "cormorantgaramond/CormorantGaramond-Italic%5Bwght%5D.ttf",
    "lora.ttf": "lora/Lora%5Bwght%5D.ttf",
    "lora-italic.ttf": "lora/Lora-Italic%5Bwght%5D.ttf",
    "barlow-400.ttf": "barlowcondensed/BarlowCondensed-Regular.ttf",
    "barlow-600.ttf": "barlowcondensed/BarlowCondensed-SemiBold.ttf",
    "mono.ttf": "jetbrainsmono/JetBrainsMono%5Bwght%5D.ttf",
}

# (RUST_NAME, ttf, weight-axis (None = static), italic)
VARIANTS = [
    ("CORMORANT_400", "cormorant.ttf", 400, False),
    ("CORMORANT_600", "cormorant.ttf", 600, False),
    ("CORMORANT_I_400", "cormorant-italic.ttf", 400, True),
    ("LORA_400", "lora.ttf", 400, False),
    ("LORA_I_400", "lora-italic.ttf", 400, True),
    ("BARLOW_400", "barlow-400.ttf", None, False),
    ("BARLOW_600", "barlow-600.ttf", None, False),
    ("MONO_400", "mono.ttf", 400, False),
]
SIZES = [11, 14, 16, 24]
FIRST, LAST = 0x20, 0x7E  # printable ASCII


def fetch():
    os.makedirs(FONTDIR, exist_ok=True)
    for fn, path in TTFS.items():
        dst = os.path.join(FONTDIR, fn)
        if os.path.exists(dst) and os.path.getsize(dst) > 1000:
            continue
        url = RAW + path
        sys.stdout.write(f"downloading {fn} ...\n")
        sys.stdout.flush()
        urllib.request.urlretrieve(url, dst)


def load(ttf, size, weight):
    f = ImageFont.truetype(os.path.join(FONTDIR, ttf), size)
    if weight is not None:
        try:
            f.set_variation_by_axes([weight])
        except Exception:
            pass
    return f


def raster(font):
    """Return (height, [(advance, width, rows_bytes_list), ...]) for ASCII."""
    ascent, descent = font.getmetrics()
    height = ascent + descent
    glyphs = []
    for code in range(FIRST, LAST + 1):
        ch = chr(code)
        advance = int(round(font.getlength(ch)))
        if advance < 1:
            advance = max(1, int(round(size_of(font) / 3)))
        w = advance
        img = Image.new("L", (w, height), 0)
        d = ImageDraw.Draw(img)
        d.text((0, ascent), ch, font=font, fill=255, anchor="ls")
        px = img.load()
        row_bytes = (w + 7) // 8
        data = bytearray()
        for y in range(height):
            row = bytearray(row_bytes)
            for x in range(w):
                if px[x, y] > 110:
                    row[x >> 3] |= 0x80 >> (x & 7)
            data += row
        glyphs.append((advance, w, bytes(data)))
    return height, glyphs


def size_of(font):
    return getattr(font, "size", 16)


def main():
    fetch()
    blocks = []          # rust BitmapFont statics
    glyph_consts = []    # rust glyph-meta arrays
    data_blob = bytearray()

    for name, ttf, weight, _ital in VARIANTS:
        for size in SIZES:
            font = load(ttf, size, weight)
            height, glyphs = raster(font)
            meta = []
            for advance, w, data in glyphs:
                off = len(data_blob)
                data_blob += data
                meta.append((advance, w, off, len(data)))
            const = f"{name}_{size}"
            metarr = ", ".join(f"G({a},{w},{o},{l})" for (a, w, o, l) in meta)
            glyph_consts.append(f"static {const}_G: [G; 95] = [{metarr}];")
            blocks.append(
                f"pub static {const}: BitmapFont = BitmapFont {{ height: {height}, "
                f"glyphs: &{const}_G, bits: FONT_BITS }};"
            )

    with open(OUT, "w") as f:
        f.write("//! GENERATED by scripts/gen_fonts.py — do not edit by hand.\n")
        f.write("//! 1-bpp bitmap glyphs for printable ASCII (0x20..0x7E).\n\n")
        f.write("#![allow(clippy::all)]\n\n")
        f.write("pub struct BitmapFont {\n    pub height: u16,\n"
                "    pub glyphs: &'static [G; 95],\n    pub bits: &'static [u8],\n}\n\n")
        # G(advance, width, offset, len)
        f.write("#[derive(Clone, Copy)]\n")
        f.write("pub struct G(pub u8, pub u8, pub u32, pub u16);\n\n")
        # the shared bit blob
        f.write("static FONT_BITS: &[u8] = &[\n")
        for i in range(0, len(data_blob), 24):
            f.write("    " + ",".join(str(b) for b in data_blob[i:i + 24]) + ",\n")
        f.write("];\n\n")
        for g in glyph_consts:
            f.write(g + "\n")
        f.write("\n")
        for b in blocks:
            f.write(b + "\n")

    sys.stdout.write(f"wrote {OUT}: {len(VARIANTS)*len(SIZES)} fonts, "
                     f"{len(data_blob)} bytes of glyph data\n")


if __name__ == "__main__":
    main()
