#!/usr/bin/env python3
"""Generate src/mp3/tables.rs from the public-domain pdmp3.c reference.

The big Huffman code-tree array (g_huffman_table) and the 512-tap synthesis
window (g_synth_dtbl) are too large/error-prone to transcribe by hand, so we
extract them verbatim from vendor/pdmp3.c. The small tables (bitrates, sf-band
indices, scalefac sizes, antialias cs/ca, intensity ratios) are emitted inline.
pdmp3 is Unlicense (public domain); see vendor/pdmp3.c header.
"""
import re
import sys
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "vendor", "pdmp3.c")
OUT = os.path.join(ROOT, "src", "mp3", "tables.rs")


def strip_comments(s):
    s = re.sub(r"/\*.*?\*/", "", s, flags=re.S)
    s = re.sub(r"//[^\n]*", "", s)
    return s


def extract_array(text, name):
    """Return the list of integer tokens inside `name[...] = { ... };`.
    `text` must already be comment-stripped (so braces in comments don't fool us)."""
    i = text.index(name)
    i = text.index("{", i)
    depth = 0
    j = i
    while j < len(text):
        if text[j] == "{":
            depth += 1
        elif text[j] == "}":
            depth -= 1
            if depth == 0:
                break
        j += 1
    body = text[i + 1 : j]
    return [int(t, 0) for t in re.findall(r"0[xX][0-9a-fA-F]+|-?\d+", body)]


def main():
    text = strip_comments(open(SRC).read())

    # g_huffman_table: flat array of u16 tree nodes (hex in source).
    huff = extract_array(text, "g_huffman_table[]")

    # g_synth_dtbl: 512 floats.
    raw = text[text.index("g_synth_dtbl[512]") :]
    raw = raw[raw.index("{") + 1 : raw.index("}")]
    dtbl = [x for x in re.findall(r"-?\d+\.\d+", strip_comments(raw))]
    assert len(dtbl) == 512, f"dtbl has {len(dtbl)} entries"

    # g_huffman_main: (offset, treelen, linbits) per table. Parse the C initializer.
    mblock = text[text.index("g_huffman_main [34]") :]
    mblock = mblock[mblock.index("{") :]
    rows = re.findall(r"\{\s*(NULL|g_huffman_table\s*\+?\s*\d*)\s*,\s*(\d+)\s*,\s*(\d+)\s*\}", mblock)
    assert len(rows) == 34, f"huffman_main has {len(rows)} rows"
    main_idx = []
    for ptr, treelen, linbits in rows:
        if ptr == "NULL":
            off = 0
        else:
            m = re.search(r"\+\s*(\d+)", ptr)
            off = int(m.group(1)) if m else 0
        main_idx.append((off, int(treelen), int(linbits)))

    with open(OUT, "w") as f:
        f.write("//! MP3 decode tables, generated by scripts/gen_mp3_tables.py from the\n")
        f.write("//! public-domain pdmp3.c (Unlicense). Do not edit by hand.\n\n")

        f.write(f"pub const HUFF: [u16; {len(huff)}] = [\n")
        for k in range(0, len(huff), 12):
            f.write("    " + ", ".join(str(x) for x in huff[k : k + 12]) + ",\n")
        f.write("];\n\n")

        f.write("/// (offset into HUFF, treelen, linbits) for tables 0..=33.\n")
        f.write("pub const HUFF_MAIN: [(u16, u16, u8); 34] = [\n")
        for off, tl, lb in main_idx:
            f.write(f"    ({off}, {tl}, {lb}),\n")
        f.write("];\n\n")

        f.write(f"pub const SYNTH_DTBL: [f32; 512] = [\n")
        for k in range(0, 512, 6):
            f.write("    " + ", ".join(f"{x}" for x in dtbl[k : k + 6]) + ",\n")
        f.write("];\n\n")

        # Small inline tables (read from pdmp3 but tiny, embed directly).
        f.write("/// MPEG1 Layer III bitrates (kbps*1000) indexed by bitrate_index 0..15.\n")
        f.write("pub const BITRATES_L3: [u32; 15] = [\n")
        f.write("    0, 32000, 40000, 48000, 56000, 64000, 80000, 96000,\n")
        f.write("    112000, 128000, 160000, 192000, 224000, 256000, 320000,\n")
        f.write("];\n\n")
        f.write("pub const SAMPLE_RATES: [u32; 3] = [44100, 48000, 32000];\n\n")
        f.write("/// (slen1, slen2) per scalefac_compress 0..15.\n")
        f.write("pub const SCALEFAC_SIZES: [(u8, u8); 16] = [\n")
        f.write("    (0,0),(0,1),(0,2),(0,3),(3,0),(1,1),(1,2),(1,3),\n")
        f.write("    (2,1),(2,2),(2,3),(3,1),(3,2),(3,3),(4,2),(4,3),\n")
        f.write("];\n\n")
        f.write("/// Scalefactor band indices [sfreq][long 23 / short 14].\n")
        f.write("pub const SFB_LONG: [[u16; 23]; 3] = [\n")
        f.write("    [0,4,8,12,16,20,24,30,36,44,52,62,74,90,110,134,162,196,238,288,342,418,576],\n")
        f.write("    [0,4,8,12,16,20,24,30,36,42,50,60,72,88,106,128,156,190,230,276,330,384,576],\n")
        f.write("    [0,4,8,12,16,20,24,30,36,44,54,66,82,102,126,156,194,240,296,364,448,550,576],\n")
        f.write("];\n\n")
        f.write("pub const SFB_SHORT: [[u16; 14]; 3] = [\n")
        f.write("    [0,4,8,12,16,22,30,40,52,66,84,106,136,192],\n")
        f.write("    [0,4,8,12,16,22,28,38,50,64,80,100,126,192],\n")
        f.write("    [0,4,8,12,16,22,30,42,58,78,104,138,180,192],\n")
        f.write("];\n\n")
        f.write("pub const PRETAB: [u8; 21] = [0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,2,2,3,3,3,2];\n\n")
        f.write("pub const ANTIALIAS_CS: [f32; 8] = [\n")
        f.write("    0.857493,0.881742,0.949629,0.983315,0.995518,0.999161,0.999899,0.999993,\n")
        f.write("];\n")
        f.write("pub const ANTIALIAS_CA: [f32; 8] = [\n")
        f.write("    -0.514496,-0.471732,-0.313377,-0.181913,-0.094574,-0.040966,-0.014199,-0.003700,\n")
        f.write("];\n\n")
        f.write("pub const IS_RATIOS: [f32; 6] = [0.0,0.267949,0.577350,1.0,1.732051,3.732051];\n\n")

        # --- Computed tables (the kernel has no libm; precompute fixed cos/sin) ---
        import math
        PI = math.pi

        # IMDCT sine windows g_imdct_win[4][36] (block types 0,1,3 long; 2 short).
        win = [[0.0] * 36 for _ in range(4)]
        for i in range(36):
            win[0][i] = math.sin(PI / 36 * (i + 0.5))
        for i in range(18):
            win[1][i] = math.sin(PI / 36 * (i + 0.5))
        for i in range(18, 24):
            win[1][i] = 1.0
        for i in range(24, 30):
            win[1][i] = math.sin(PI / 12 * (i + 0.5 - 18.0))
        for i in range(30, 36):
            win[1][i] = 0.0
        for i in range(12):
            win[2][i] = math.sin(PI / 12 * (i + 0.5))
        for i in range(12, 36):
            win[2][i] = 0.0
        for i in range(6):
            win[3][i] = 0.0
        for i in range(6, 12):
            win[3][i] = math.sin(PI / 12 * (i + 0.5 - 6.0))
        for i in range(12, 18):
            win[3][i] = 1.0
        for i in range(18, 36):
            win[3][i] = math.sin(PI / 36 * (i + 0.5))

        def emit_2d(name, rows, cols, data):
            f.write(f"pub const {name}: [[f32; {cols}]; {rows}] = [\n")
            for r in range(rows):
                f.write("    [" + ",".join(f"{data[r][c]:.9}" for c in range(cols)) + "],\n")
            f.write("];\n\n")

        emit_2d("IMDCT_WIN", 4, 36, win)

        # IMDCT cosine matrices. Long: N=36, cos(PI/(2N)*(2p+1+N/2)*(2m+1)), m,p < N (m<N/2).
        cos_l = [[math.cos(PI / 72 * (2 * p + 1 + 18) * (2 * m + 1)) for p in range(36)] for m in range(18)]
        emit_2d("COS_L", 18, 36, cos_l)
        # Short: N=12, m,p < 12 (m < N/2=6).
        cos_s = [[math.cos(PI / 24 * (2 * p + 1 + 6) * (2 * m + 1)) for p in range(12)] for m in range(6)]
        emit_2d("COS_S", 6, 12, cos_s)

        # Subband synthesis matrix n_win[64][32] = cos((16+i)*(2j+1)*PI/64).
        n_win = [[math.cos((16 + i) * (2 * j + 1) * (PI / 64.0)) for j in range(32)] for i in range(64)]
        emit_2d("N_WIN", 64, 32, n_win)

        # Requantize_Pow_43 table: is^(4/3) for is in 0..=8206 (15 + max linbits 8191).
        f.write("pub const POW43: [f32; 8207] = [\n")
        p43 = [0.0] + [math.pow(i, 4.0 / 3.0) for i in range(1, 8207)]
        for k in range(0, 8207, 8):
            f.write("    " + ",".join(f"{p43[i]:.7}" for i in range(k, min(k + 8, 8207))) + ",\n")
        f.write("];\n")

    print(f"wrote {OUT}: HUFF={len(huff)}, DTBL=512, HUFF_MAIN=34, +computed cos/win/pow43")


if __name__ == "__main__":
    main()
